# CLI Tool Configuration
# Settings for the Kaggle + Drive CLI tool itself (NOT individual projects)

cli_tool:
  name: "Kaggle CLI Tools"
  version: "1.0.0"
  description: "Advanced CLI automation for Kaggle kernels with Google Drive integration"

# File paths and locations
paths:
  # Configuration files
  config_dir: "./config"
  metadata_file: "./config/metadata.json"
  drive_config_file: "./config/drive_config.json"
  
  # API credentials
  kaggle_credentials: "./config/kaggle_key.json"
  drive_credentials: "./config/drive_key.json"
  drive_token: "./config/token.json"
  
  # Project directories
  scripts_dir: "./scripts"
  templates_dir: "./templates"
  temp_dir: "./temp_outputs"
  
  # Template files
  kernel_template: "./templates/script.py"
  upload_template: "./templates/upload-to-drive.py"
  kernel_metadata_template: "./templates/kernel-metadata.json"

# Google Drive settings
google_drive:
  scopes:
    - "https://www.googleapis.com/auth/drive"
  
  # Folder structure to create in Drive
  folder_structure:
    root: "Kaggle-CLI"
    subfolders:
      - "Projects"
      - "Datasets" 
      - "Outputs"
      - "Archives"
  
  # Upload settings
  upload:
    resumable: true
    chunk_size: 1048576  # 1MB chunks

# Kaggle settings
kaggle:
  # Default kernel settings
  kernel_defaults:
    language: "python"
    kernel_type: "script"
    enable_gpu: true
    enable_internet: false
    is_private: true
  
  # Polling settings for kernel status
  polling:
    initial_wait: 30      # seconds to wait before first status check
    check_interval: 60    # seconds between status checks
    max_wait_time: 3600   # max seconds to wait for completion

# CLI settings
cli:
  # Commands and their descriptions
  commands:
    # Core CLI commands
    setup: "Initialize Google Drive folder structure"
    status: "Show Kaggle kernels and sync status"
    list: "List all your Kaggle kernels"
    sync: "Sync kernel outputs to Google Drive"
    
    # Project management commands
    create-project: "Create new project with config on Google Drive"
    list-projects: "List all projects stored on Google Drive"
    project-status: "Show detailed status for a specific project"
    
    # File operations
    upload: "Upload files to Google Drive"
    download: "Download files from Google Drive"
  
  # Output formatting
  output:
    use_emojis: true
    show_timestamps: true
    max_kernels_display: 5
    max_history_display: 3

# Dependencies
dependencies:
  python_packages:
    - "kaggle>=1.5.12"
    - "google-api-python-client>=2.0.0"
    - "google-auth-httplib2>=0.1.0"
    - "google-auth-oauthlib>=0.5.0"
    - "pandas>=1.3.0"
    - "numpy>=1.21.0"
    - "matplotlib>=3.4.0"
    - "seaborn>=0.11.0"
    - "pyyaml>=6.0"

# Security settings
security:
  # Files to never commit to git
  sensitive_files:
    - "*_key.json"
    - "kaggle.json"
    - "credentials.json"
    - "token.json"
    - "*.key"
    - "*.secret"
  
  # Directories to exclude
  sensitive_dirs:
    - ".kaggle/"
    - "temp_outputs/"
    - "__pycache__/"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./config/cli.log"